name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        build-type: [Release, Debug, RelWithDebInfo, MinSizeRel]
    

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: "(pkgs): Update package lists"
      run: sudo apt-get update
    - name: "(pkgs): Upgrade packages"
      run: sudo apt-get upgrade -y
    - name: "(pkgs): Install toolchain"
      run: sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib python3 git


    - uses: actions/checkout@v3
      with:
        # Checkout submodules (non-recursive)
        submodules: 'true'

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}/src

    - name: Build
      # Build the program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }}

    - name: "Upload Build Artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.build-type }}
        path: |
          build/main_*.*
    
    - name: "(deploy/main): Create variable with lowercase build type"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo "BUILD_TYPE_LOWERCASE=$(echo "${{ matrix.build-type }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    
    - name: "(deploy/main): Read out build type variable"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo "Found build variable '$BUILD_TYPE_LOWERCASE'"
    
    - name: "(deploy/main): Create directory structure for GitHub Pages deployment"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: mkdir -p pages-deploy/$BUILD_TYPE_LOWERCASE && cp build/main_*.* pages-deploy/$BUILD_TYPE_LOWERCASE

    - name: "(deploy/main): Create sha.txt file"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: git rev-parse HEAD > pages-deploy/$BUILD_TYPE_LOWERCASE/sha.txt

    - name: "(deploy/main): Upload Build Artifacts to GitHub Pages"
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: pages-deploy/${{ env.BUILD_TYPE_LOWERCASE }}
        destination_dir: builds/main/${{ env.BUILD_TYPE_LOWERCASE }}
        keep_files: true

#    - name: Test
#      working-directory: ${{github.workspace}}/build
#      # Execute tests defined by the CMake configuration.
#      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#      run: ctest -C ${{ matrix.build-type }}
