name: Mirror

on: ["push", "delete"]

jobs:
  igem-gitlab:
    name: iGEM GitLab

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all branches and tags

      - name: Mirror repository
        uses: genoswitch/repository-mirroring-action@a76d61cd1d28ee9e2ab5b6b19cc825736f02b38d
        with:
          target_repo_url: git@gitlab.igem.org:jcxldn/City-of-London-UK_firmware.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_KEY }}

  merge:
    name: Merge

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MERGE_PAT }}
          repository: genoswitch/software-judging
          event-type: merge_repo
          client-payload: '{"repo": "firmware"}'
